spring:
  application:
    name: AdaptationFlow

  datasource:
    url: jdbc:postgresql://localhost/test1
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  data:
    jpa:
      repositories:
        enabled: true
  liquibase:
    enabled: true
    change-log: classpath:/db/liquibase/master.xml
jwt:
  secret: "your-256-bit-secret-your-very-long-secret-key-for-hmac"
  expiration-ms: 3600000  # время жизни токена в миллисекундах (1 час)