spring:
  application:
    name: AdaptationFlow

  datasource:
    url: jdbc:postgresql://localhost/test1
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  data:
    jpa:
      repositories:
        enabled: true
  liquibase:
    enabled: true
    change-log: classpath:/db/liquibase/master.xml
jwt:
  secret: "your-256-bit-secret-your-very-long-secret-key-for-hmac"
  expiration-ms: 360000000  # время жизни токена в миллисекундах (10 час)
logging:
  level:
    root: INFO                 # общий уровень логов
    com.project.adaptationflow.config.JwtAuthenticationFilter: DEBUG  # подробное логирование фильтра JWT
    com.project.adaptationflow: DEBUG   # подробное логирование всего твоего пакета
    org.springframework.security: INFO  # можно понизить уровень логов Spring Security, если много шума
