spring:
  application:
    name: ${APP_NAME}

  datasource:
    url: jdbc:postgresql://localhost/test1
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  data:
    jpa:
      repositories:
        enabled: true
  liquibase:
    enabled: true
    change-log: classpath:/db/liquibase/master.xml